coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        informational: true

ignore:
  - "**/*.d.ts"
  - "**/types.ts"
  - "**/defaults.ts"
  - "**/constants.ts"
  - "src/index.ts"
  - "src/shared/tests/**"
