name: 'GitHub Star Tracker'
description: 'Track star count changes across your repositories with historical reports and badges'
author: 'Ferran Buireu'

branding:
  icon: 'star'
  color: 'yellow'

inputs:
  github-token:
    description: 'Personal Access Token (PAT) with repo or public_repo scope - GITHUB_TOKEN does not work'
    required: true

  github-api-url:
    description: 'GitHub API base URL for GitHub Enterprise Server (e.g. https://github.example.com/api/v3). Auto-detected on GHES runners.'
    required: false
    default: ''

  config-path:
    description: 'Path to the configuration file (relative to repo root)'
    required: false
    default: 'star-tracker.yml'

  visibility:
    description: 'Repository visibility filter: public, private, all, or owned (only repos you own) (overrides config file)'
    required: false
    default: ''

  include-archived:
    description: 'Include archived repositories (overrides config file)'
    required: false
    default: ''

  include-forks:
    description: 'Include forked repositories (overrides config file)'
    required: false
    default: ''

  exclude-repos:
    description: 'Comma-separated list of repository names or regex patterns (e.g. /^test-.*/) to exclude (overrides config file)'
    required: false
    default: ''

  only-repos:
    description: 'Comma-separated list of repository names to exclusively track (overrides config file)'
    required: false
    default: ''

  min-stars:
    description: 'Only track repos with at least this many stars (overrides config file)'
    required: false
    default: ''

  data-branch:
    description: 'Branch name for storing tracking data'
    required: false
    default: 'star-tracker-data'

  max-history:
    description: 'Maximum number of snapshots to keep in history'
    required: false
    default: '52'

  smtp-host:
    description: 'SMTP server host — providing this enables built-in email notifications'
    required: false
    default: ''

  smtp-port:
    description: 'SMTP server port'
    required: false
    default: '587'

  smtp-username:
    description: 'SMTP authentication username'
    required: false
    default: ''

  smtp-password:
    description: 'SMTP authentication password'
    required: false
    default: ''

  email-to:
    description: 'Email recipient address'
    required: false
    default: ''

  email-from:
    description: 'Email sender name or address'
    required: false
    default: 'GitHub Star Tracker'

  send-on-no-changes:
    description: 'Send email even when no star changes are detected'
    required: false
    default: 'false'

  include-charts:
    description: 'Include star trend charts in reports (true/false)'
    required: false
    default: 'true'

  notification-threshold:
    description: 'Star change threshold before sending notification: 0 (every run), a number (e.g. 5), or "auto" (adaptive)'
    required: false
    default: '0'

  locale:
    description: 'Language for reports and emails: en, es, ca, it'
    required: false
    default: 'en'

  top-repos:
    description: 'Number of top repositories to feature in charts and forecasts (by star count)'
    required: false
    default: '10'

  track-stargazers:
    description: 'Track individual stargazers and show new ones in reports (true/false)'
    required: false
    default: 'false'

outputs:
  report:
    description: 'Markdown report of star changes'

  report-html:
    description: 'HTML report of star changes (for email)'

  total-stars:
    description: 'Total star count across all tracked repositories'

  stars-changed:
    description: 'Whether any star counts changed since last run (true/false)'

  new-stars:
    description: 'Number of new stars gained since last run'

  lost-stars:
    description: 'Number of stars lost since last run'

  should-notify:
    description: 'Whether the notification threshold was reached (true/false)'

  report-csv:
    description: 'CSV report of star changes'

  new-stargazers:
    description: 'Number of new stargazers detected since last run (0 if tracking disabled)'

runs:
  using: 'node24'
  main: 'dist/index.js'
