import type { ComparisonResults } from './types';

const COLORS = {
  positive: '#28a745',
  negative: '#d73a49',
  neutral: '#6a737d',
  link: '#0366d6',
  text: '#24292e',
  accent: '#dfb317',
  tableHeaderBg: '#f6f8fa',
  tableHeaderBorder: '#e1e4e8',
  cellBorder: '#eee',
  white: '#fff',
} as const;

export function deltaIndicator(delta: number): string {
  if (delta > 0) return `+${delta}`;
  if (delta < 0) return `${delta}`;
  return '0';
}

export function trendIcon(delta: number): string {
  if (delta > 0) return '\u2B06\uFE0F';
  if (delta < 0) return '\u2B07\uFE0F';
  return '\u2796';
}

interface GenerateReportParams {
  results: ComparisonResults;
  previousTimestamp: string | null;
}

export function generateMarkdownReport({
  results,
  previousTimestamp,
}: GenerateReportParams): string {
  const { repos, summary } = results;
  const now = new Date().toISOString().split('T')[0];
  const prev = previousTimestamp ? previousTimestamp.split('T')[0] : 'first run';

  const activeRepos = repos.filter((repo) => !repo.isRemoved);
  const newRepos = repos.filter((repo) => repo.isNew);
  const removedRepos = repos.filter((repo) => repo.isRemoved);
  const sorted = [...activeRepos].sort((repoA, repoB) => repoB.current - repoA.current);

  const header = [
    '# Star Tracker Report',
    '',
    `**${now}** | Total: **${summary.totalStars}** stars | Change: **${deltaIndicator(summary.totalDelta)}**`,
    '',
  ];

  const comparison = prev === 'first run' ? [] : [`> Compared to snapshot from ${prev}`, ''];

  const repoTable =
    activeRepos.length > 0
      ? [
          '## Repositories',
          '',
          '| Repository | Stars | Change | Trend |',
          '|:-----------|------:|-------:|:-----:|',
          ...sorted.map((repo) => {
            const badge = repo.isNew ? ' `NEW`' : '';
            return `| [${repo.fullName}](https://github.com/${repo.fullName})${badge} | ${repo.current} | ${deltaIndicator(repo.delta)} | ${trendIcon(repo.delta)} |`;
          }),
          '',
        ]
      : [];

  const newSection =
    newRepos.length > 0
      ? [
          '## New Repositories',
          '',
          ...newRepos.map(
            (repo) =>
              `- [${repo.fullName}](https://github.com/${repo.fullName}) — ${repo.current} stars`,
          ),
          '',
        ]
      : [];

  const removedSection =
    removedRepos.length > 0
      ? [
          '## Removed Repositories',
          '',
          ...removedRepos.map((repo) => `- ${repo.fullName} — was ${repo.previous} stars`),
          '',
        ]
      : [];

  const summarySection =
    summary.totalDelta === 0
      ? []
      : [
          '## Summary',
          '',
          `- **Stars gained:** ${summary.newStars}`,
          `- **Stars lost:** ${summary.lostStars}`,
          `- **Net change:** ${deltaIndicator(summary.totalDelta)}`,
          '',
        ];

  const footer = [
    '---',
    `*Generated by [GitHub Star Tracker](https://github.com/fbuireu/github-star-tracker) on ${new Date().toISOString()}*`,
  ];

  return [
    ...header,
    ...comparison,
    ...repoTable,
    ...newSection,
    ...removedSection,
    ...summarySection,
    ...footer,
  ].join('\n');
}

export function generateHtmlReport({ results, previousTimestamp }: GenerateReportParams): string {
  const { repos, summary } = results;
  const now = new Date().toISOString().split('T')[0];
  const prev = previousTimestamp ? previousTimestamp.split('T')[0] : 'first run';

  const activeRepos = repos.filter((repo) => !repo.isRemoved);
  const sorted = [...activeRepos].sort((repoA, repoB) => repoB.current - repoA.current);

  const deltaColor = (delta: number): string => {
    if (delta > 0) return COLORS.positive;
    if (delta < 0) return COLORS.negative;
    return COLORS.neutral;
  };

  const rows = sorted
    .map((repo) => {
      const badge = repo.isNew
        ? ` <span style="background:${COLORS.positive};color:${COLORS.white};padding:1px 6px;border-radius:3px;font-size:11px;">NEW</span>`
        : '';
      return `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid ${COLORS.cellBorder};">
          <a href="https://github.com/${repo.fullName}" style="color:${COLORS.link};text-decoration:none;">${repo.fullName}</a>${badge}
        </td>
        <td style="padding:8px 12px;border-bottom:1px solid ${COLORS.cellBorder};text-align:right;">${repo.current}</td>
        <td style="padding:8px 12px;border-bottom:1px solid ${COLORS.cellBorder};text-align:right;color:${deltaColor(repo.delta)};font-weight:600;">
          ${deltaIndicator(repo.delta)}
        </td>
      </tr>`;
    })
    .join('');

  const removedRepos = repos.filter((repo) => repo.isRemoved);
  const removedSection =
    removedRepos.length > 0
      ? `
      <div style="margin-top:16px;">
        <h3 style="color:${COLORS.negative};font-size:14px;">Removed Repositories</h3>
        <ul>${removedRepos.map((repo) => `<li>${repo.fullName} — was ${repo.previous} stars</li>`).join('')}</ul>
      </div>`
      : '';

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;color:${COLORS.text};">
  <div style="text-align:center;padding:20px 0;border-bottom:2px solid ${COLORS.accent};">
    <h1 style="margin:0;font-size:24px;">Star Tracker Report</h1>
    <p style="color:${COLORS.neutral};margin:8px 0 0;">${now} ${prev === 'first run' ? '| First snapshot' : `| vs ${prev}`}</p>
  </div>

  <div style="display:flex;justify-content:space-around;padding:20px 0;text-align:center;">
    <div>
      <div style="font-size:28px;font-weight:700;">${summary.totalStars}</div>
      <div style="color:${COLORS.neutral};font-size:12px;">Total Stars</div>
    </div>
    <div>
      <div style="font-size:28px;font-weight:700;color:${deltaColor(summary.totalDelta)};">${deltaIndicator(summary.totalDelta)}</div>
      <div style="color:${COLORS.neutral};font-size:12px;">Net Change</div>
    </div>
    <div>
      <div style="font-size:28px;font-weight:700;color:${COLORS.positive};">${summary.newStars}</div>
      <div style="color:${COLORS.neutral};font-size:12px;">Gained</div>
    </div>
    <div>
      <div style="font-size:28px;font-weight:700;color:${COLORS.negative};">${summary.lostStars}</div>
      <div style="color:${COLORS.neutral};font-size:12px;">Lost</div>
    </div>
  </div>

  <table style="width:100%;border-collapse:collapse;margin-top:16px;">
    <thead>
      <tr style="background:${COLORS.tableHeaderBg};">
        <th style="padding:8px 12px;text-align:left;border-bottom:2px solid ${COLORS.tableHeaderBorder};">Repository</th>
        <th style="padding:8px 12px;text-align:right;border-bottom:2px solid ${COLORS.tableHeaderBorder};">Stars</th>
        <th style="padding:8px 12px;text-align:right;border-bottom:2px solid ${COLORS.tableHeaderBorder};">Change</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>

  ${removedSection}

  <div style="margin-top:24px;padding-top:16px;border-top:1px solid ${COLORS.cellBorder};text-align:center;color:${COLORS.neutral};font-size:12px;">
    Generated by <a href="https://github.com/fbuireu/github-star-tracker" style="color:${COLORS.link};">GitHub Star Tracker</a>
  </div>
</body>
</html>`;
}
